### ISSUE TITLE
enhance release documentation?

### ISSUE THREAD

**Issue by nauni77** [gematik/ref-eRp-FD-Server#23]
Hello, 
first I want to say thanks for your bugfixes and improvements. Now I had a few times problems to switch from release "0.(x).0" to "0.(x+1).0". You have a documentation about the new version at:

https://github.com/gematik/ref-eRp-FD-Server/blob/master/ReleaseNotes.md

Maybe you can add more information what the customers have to make switching to the new Release-Tag. For example:

I build the container with 0.12.0 and everything works fine. Now I only switch to the 0.13.0 and rebuild the container I got the error (while starting the server process):

```
2021-03-08T10:19:58.119728589+01:00 WARN ref_erx_fd_server::tasks::tsl::update - Unable to fetch TSL (https://download.tsl.ti-dienste.de/): Reqwest Error: error sending request for url (https://download.tsl.ti-dienste.de/): error trying to connect: dns error: cancelled
2021-03-08T10:19:58.629403814+01:00 INFO ref_erx_fd_server::tasks::tsl::update - TSL updated: file:///application/server/examples/N-BNetzA-VL-seq24.xml
Error: PukTokenError(OpenSslError(ErrorStack([Error { code: 151584876, library: "PEM routines", function: "get_name", reason: "no start line", file: "../crypto/pem/pem_lib.c", line: 745, data: "Expecting: CERTIFICATE" }])))
2021-03-08 10:19:58,638 INFO exited: gematik (exit status 1; not expected)
2021-03-08 10:19:59,641 INFO spawned: 'gematik' with pid 97
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/ref-erx-fd-server -l '0.0.0.0:3000' --enc-key /application/certs/enc_id --enc-cert /application/certs/enc_id.cert --sig-key /application/certs/sig_id --sig-cert /application/certs/sig_id.cert --token 'file:///application/certs/idp_id.pub' --tsl 'https://download.tsl.ti-dienste.de' --bnetza 'file:///application/server/examples/N-BNetzA-VL-seq24.xml'`
```

In future maybe you can add additional information to the release notes? Do you have a idear whats going wrong?

Regards, Oli

**Comment by Gematik-Entwicklung** [comment]
Hi Oli,

you can find all information you need in the README.md. Unfortunately we forgot to update the command line arguments to start the service with. The "--token" parameter now expects a X509 certificate instead of the a public key. We have already fixed the README. It will be updated in our next release. Sorry for the circumstances.

Bet regards,
gematik Dev-Team.

**Comment by nauni77** [comment]
Hello, 
if I use "--token" with the certificate it works - the server starts as expected.
Thanks.

**Comment by nauni77** [comment]
This time (0.14.0) you forgot to add the additional requirement of the package: libxml2-dev

Maybe you want to add this to the README.md. Now you need to compile with linux:

```
-   On linux you can install the depdendencies using the following command

            $ apt-get install libssl1.1 libssl-dev libxml2-dev
```

Regards, Oli

**Comment by Gematik-Entwicklung** [comment]
Thanks, will be fixed in the next release :)
